
export const COST_PARKING_PASS_FORGOT = 200; // NO INFORMATION
export const COST_EXTRA_PARKING_PASS = 200; // NO INFORMATION
export const COST_EXTRA_PARKING_PASS_FORGOT = 200; // NO INFORMATION
export const COST_EXTRA_PEOPLE = 380;
export const COST_KEY_FORGOT = 90;
export const COST_BREAKFAST = 200;
